apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-processor
  annotations:
    kubernetes.io/change-cause: "Updated at $(date +'%Y-%m-%d %H:%M:%S')"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-processor
  template:
    metadata:
      labels:
        app: stats-processor
      annotations:
        kubernetes.io/change-cause: "Updated at $(date +'%Y-%m-%d %H:%M:%S')"
    spec:
      containers:
        - name: stats-processor
          image: recklessop/zp-stats-pusher:latest
          imagePullPolicy: Always
          env:
          - name: VCENTER_HOST
            valueFrom:
              configMapKeyRef:
                name: vcenter-config
                key: VCENTER_HOST
          - name: VCENTER_USERNAME
            valueFrom:
              configMapKeyRef:
                name: vcenter-config
                key: VCENTER_USERNAME
          - name: VCENTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vcenter-secret
                key: VCENTER_PASSWORD
          - name: REDIS_SERVER
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: REDIS_SERVER
          - name: INFLUXDB_HOST
            valueFrom:
              configMapKeyRef:
                name: influxdb-config
                key: INFLUXDB_HOST
          - name: INFLUXDB_PORT
            valueFrom:
              configMapKeyRef:
                name: influxdb-config
                key: INFLUXDB_PORT
          - name: INFLUXDB_TOKEN
            valueFrom:
              configMapKeyRef:
                name: influxdb-config
                key: INFLUXDB_TOKEN
          - name: INFLUXDB_ORG
            valueFrom:
              configMapKeyRef:
                name: influxdb-config
                key: INFLUXDB_ORG
          - name: INFLUXDB_BUCKET
            valueFrom:
              configMapKeyRef:
                name: influxdb-config
                key: INFLUXDB_BUCKET
