apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_DEFAULTS_PATHS_PROVISIONING: /etc/grafana/provisioning
  GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "true"
  GF_PLUGINS_ENABLE_ALPHA: "true"
