---
apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=
  GF_SECURITY_ADMIN_USER: YWRtaW4=
kind: Secret
  name: grafana-secret
  namespace: zplanner
type: Opaque
---
apiVersion: v1
data:
  VCENTER_PASSWORD: WmVydG9kYXRhOTg3IQ==
kind: Secret
  name: vcenter-secret
  namespace: zplanner
type: Opaque
