apiVersion: v1
kind: ConfigMap
metadata:
  name: vcenter-config
data:
  VCENTER_HOST: "192.168.50.50"
  VCENTER_USERNAME: "zplannersvc@vsphere.local"
  SAMPLE_MINUTES: "5"
  JOB_EXPIRATION_MINUTES: "6"
  PROVISIONED: "False"
---
apiVersion: v1
kind: Secret
metadata:
  name: vcenter-secret
type: Opaque
stringData:
  VCENTER_PASSWORD: "password"
