apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
spec:
  template:
    spec:
      containers:
        - name: influxdb-setup
          image: influxdb:2.0
          command: ["/bin/bash", "/setup/setup.sh"]
          volumeMounts:
            - name: setup-script
              mountPath: /setup
      volumes:
        - name: setup-script
          configMap:
            name: influxdb-setup-script
      restartPolicy: OnFailure
