apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-setup-script
data:
  setup.sh: |
    #!/bin/bash
    set -e
    INFLUX_HOST=http://influxdb:8086
    INFLUXDB_SETUP_USERNAME=zplanner
    INFLUXDB_SETUP_PASSWORD=zplanner
    INFLUXDB_SETUP_ORG=zplanner
    INFLUXDB_SETUP_BUCKET=zplanner
    INFLUXDB_CONFIGMAP_NAME=influxdb-config
    INFLUXDB_SETUP_TOKEN=zplannertoken1234567890

    while ! curl -s ${INFLUX_HOST}/ping; do
      echo "Waiting for influxdb to be ready..."
      sleep 5
    done

    # Run the setup command and capture the output
    SETUP_OUTPUT=$(influx setup --username ${INFLUXDB_SETUP_USERNAME} \
                                --password ${INFLUXDB_SETUP_PASSWORD} \
                                --org ${INFLUXDB_SETUP_ORG} \
                                --bucket ${INFLUXDB_SETUP_BUCKET} \
                                --token ${INFLUXDB_SETUP_TOKEN} \
                                --host ${INFLUX_HOST} \
                                --force \
                                --json)

    # Save the output to a shared volume
    echo ${SETUP_OUTPUT} > /shared/setup_output.json
    echo "Setup output written to /shared/setup_output.json"