apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
spec:
  template:
    spec:
      containers:
        - name: influxdb-setup
          image: influxdb:2.0
          command: ["/bin/bash", "/setup/setup.sh"]
          volumeMounts:
            - name: setup-script
              mountPath: /setup
            - name: shared-data
              mountPath: /setup

        - name: json-parser
          image: bitnami/minideb
          command: ["bash", "-c", "apt-get update && apt-get install -y jq && sleep infinity"]
          volumeMounts:
            - name: shared-data
              mountPath: /setup

      restartPolicy: OnFailure
      volumes:
        - name: setup-script
          configMap:
            name: influxdb-setup-script
        - name: shared-data
          emptyDir: {}

      initContainers:
        - name: parse-token
          image: bitnami/minideb
          command: ["/bin/bash", "-c", "apt-get update && apt-get install -y jq && TOKEN=$(cat /setup/setup_output.json | jq -r '.auth.token') && echo $TOKEN"]
          volumeMounts:
            - name: shared-data
              mountPath: /setup
