apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-setup-script
data:
  setup.sh: |
    #!/bin/bash
    set -e
    INFLUX_HOST=http://localhost:8086
    INFLUXDB_SETUP_USERNAME=myuser
    INFLUXDB_SETUP_PASSWORD=mypassword
    INFLUXDB_SETUP_ORG=default-org
    INFLUXDB_SETUP_BUCKET=default-bucket
    INFLUXDB_CONFIGMAP_NAME=influxdb-config

    while ! curl -s ${INFLUX_HOST}/ping; do
      echo "Waiting for influxdb to be ready..."
      sleep 5
    done

    # Run the setup command and capture the output
    SETUP_OUTPUT=$(influx setup --username ${INFLUXDB_SETUP_USERNAME} \
                                --password ${INFLUXDB_SETUP_PASSWORD} \
                                --org ${INFLUXDB_SETUP_ORG} \
                                --bucket ${INFLUXDB_SETUP_BUCKET} \
                                --host ${INFLUX_HOST} \
                                --force \
                                --json)

    # Save the output to a shared volume
    echo ${SETUP_OUTPUT} > /setup/setup_output.json
