apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
spec:
  template:
    spec:
      containers:
        - name: influxdb-setup
          image: influxdb:2.0
          command: ["/bin/bash", "/setup/setup.sh"]
          env:
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
          volumeMounts:
            - name: setup-script
              mountPath: /setup
            - name: kube-config
              mountPath: /root/.kube/config
              subPath: config
      volumes:
        - name: setup-script
          configMap:
            name: influxdb-setup-script
        - name: kube-config
          secret:
            secretName: kube-config
      restartPolicy: OnFailure

