apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
spec:
  template:
    spec:
      initContainers:
        - name: parse-token
          image: bitnami/minideb
          command: ["/bin/bash", "-c", "apt-get update && apt-get install -y jq && TOKEN=$(cat /shared/setup_output.json | jq -r '.auth.token') && echo $TOKEN > /shared/token.txt"]
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      containers:
        - name: influxdb-setup
          image: influxdb:2.0
          command: ["/bin/bash", "/setup/setup.sh"]
          volumeMounts:
            - name: setup-script
              mountPath: /setup
            - name: shared-data
              mountPath: /shared
        - name: json-parser
          image: bitnami/minideb
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      volumes:
        - name: setup-script
          configMap:
            name: influxdb-setup-script
        - name: shared-data
          emptyDir: {}
      restartPolicy: OnFailure
